# SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

property:
  gpu-id: 0
  net-scale-factor: 0.00392156862745098
  model-color-format: 0
  onnx-file: resnet34_peoplenet_int8.onnx
  model-engine-file: resnet34_peoplenet_int8.onnx_b3_gpu0_fp32.engine
  labelfile-path: labels.txt
  int8-calib-file: resnet34_peoplenet_int8.txt
  batch-size: 3
  network-mode: 0
  num-detected-classes: 3
  interval: 0
  gie-unique-id: 1
  process-mode: 1
  network-type: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  infer-dims: 3;544;960
  parse-bbox-func-name: NvDsInferParseBbox

class-attrs-all:
  pre-cluster-threshold: 0.5
  topk: 300
  nms-iou-threshold: 0.45
