# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_alter_device_deepstream_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmp_community',
            field=models.CharField(blank=True, default='public', max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_port',
            field=models.IntegerField(default=161),
        ),
        migrations.AlterField(
            model_name='device',
            name='deepstream_pipeline',
            field=models.CharField(choices=[('main', 'Peoplenet'), ('retinaface', 'Face Recognition'), ('yolov9', 'YOLO v9'), ('trafficcamnet_lpr', 'TrafficCamNet + LPR'), ('', 'Sin pipeline')], default='main', max_length=20),
        ),
    ]
