property:
  gpu-id: 0
  net-scale-factor: 0.0078125
  offsets: 127.5;127.5;127.5
  model-color-format: 0
  onnx-file: /opt/computer_vision/models/retinaface_det10g/det_10g_batched.onnx
  labelfile-path: /opt/computer_vision/models/retinaface_det10g/labels.txt
  batch-size: 1
  network-mode: 0
  num-detected-classes: 1
  interval: 0
  gie-unique-id: 1
  process-mode: 1
  network-type: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  infer-dims: 3;640;640
  parse-bbox-func-name: NvDsInferParseCustomDet10g
  custom-lib-path: /opt/computer_vision/app/libnvdsparsebbox_det10g.so
  output-tensor-meta: 1


class-attrs-all:
  pre-cluster-threshold: 0.5
  topk: 100
  nms-iou-threshold: 0.4