# Generated by Django 6.0.7 on 2026-07-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_device_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='min_confidence',
            field=models.FloatField(default=0.25, help_text='Confianza minima de deteccion (0.0-1.0)'),
        ),
    ]
